### PR TITLE
format update for Wh

### PR DESCRIPTION
**Pull request by who7-stat6250**

### CODE REVIEW

**Review by jbettonville-stat6250 — CHANGES_REQUESTED** [review]
Changes requested:
- More than 80 characters in comment blocks on lines 40, 125, 173
- Inconsistent wrapping for titles and footnotes
- Inconsistent use of case (i.e. DATA and data both used)
- Remove all tab characters and replace with four space characters
- Run spell check to correct spelling errors
- Syntax error caused by single quote (California's) on line 170, should be two single quotes (California''s)
- Warning on line 187 about use of "ne" with quoted string
JB

**Comment by who7-stat6250** [comment]
updated file again, please review

**Review by jbettonville-stat6250 — CHANGES_REQUESTED** [review]
Program runs without errors now in SAS 9.4, however there are still some outstanding formatting issues:

* Inconsistent use of case (i.e. PROC and proc both used, along with others; check thoroughly for consistency)
* Remove all tab characters and replace with four space characters
* Run spell check to correct spelling errors

JB

**Comment by who7-stat6250** [comment]
third's time the charm

**Pull request merged**
